// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdRA3KDhvA0ykqPYdp6spK6arjFBg1G1o',
    appId: '1:362885147432:web:e1a402784b3598e8343e1d',
    messagingSenderId: '362885147432',
    projectId: 'able-cab',
    authDomain: 'able-cab.firebaseapp.com',
    storageBucket: 'able-cab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZZoiwhy-2WKNQvSb1o5wkC8xJE5JK_Ig',
    appId: '1:362885147432:android:77336d7e941dbb1e343e1d',
    messagingSenderId: '362885147432',
    projectId: 'able-cab',
    storageBucket: 'able-cab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnNv_0qPQ2HaxHkJCrB4B1JgUsyQ0RtxE',
    appId: '1:362885147432:ios:298d1683391d36b9343e1d',
    messagingSenderId: '362885147432',
    projectId: 'able-cab',
    storageBucket: 'able-cab.appspot.com',
    iosClientId: '362885147432-8drk6riedu3k1g1583ivcj9t65tmhrj7.apps.googleusercontent.com',
    iosBundleId: 'com.example.ablecab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnNv_0qPQ2HaxHkJCrB4B1JgUsyQ0RtxE',
    appId: '1:362885147432:ios:34b66496422c77e5343e1d',
    messagingSenderId: '362885147432',
    projectId: 'able-cab',
    storageBucket: 'able-cab.appspot.com',
    iosClientId: '362885147432-rv0nv9ncbb8n49s643d0pa0t7r6np5s2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ablecab.RunnerTests',
  );
}
